refiner_node:
  ros__parameters:
    half_win: 1  # 얼마나 주변 depth를 볼 것인가
    remove_space_dis: 10000  # mm

pantilt_node:
  ros__parameters:
    rate_hz: 100.0

    pan_id: 22
    pan_max_deg: 70.0
    pan_min_deg: -70.0

    tilt_id: 23
    tilt_max_deg: -5.0
    tilt_min_deg: -45.0

    scan_pan_speed_deg_s: 40.0
    scan_tilt_speed_deg_s: 40.0

    img_w: 960
    img_h: 540

    pan_dir: -1.0
    tilt_dir: 1.0

